"""add_disabled_field_to_user

Revision ID: a6b348beb400
Revises: 001
Create Date: 2026-07-19 19:35:09.742128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b348beb400'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add disabled column with default value False for SQLite compatibility
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('disabled_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled_reason')
    op.drop_column('user', 'disabled')
    # ### end Alembic commands ###
