"""add_telemetry_reading_table

Revision ID: 8c163a76a997
Revises: a6b348beb400
Create Date: 2026-08-20 23:36:21.294025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c163a76a997'
down_revision = 'a6b348beb400'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetryreading',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('anomaly', sa.Boolean(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'UPLOADED', 'MANUAL', name='telemetrysource', create_constraint=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetryreading_id'), 'telemetryreading', ['id'], unique=False)
    op.create_index(op.f('ix_telemetryreading_timestamp'), 'telemetryreading', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetryreading_user_id'), 'telemetryreading', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetryreading_user_id'), table_name='telemetryreading')
    op.drop_index(op.f('ix_telemetryreading_timestamp'), table_name='telemetryreading')
    op.drop_index(op.f('ix_telemetryreading_id'), table_name='telemetryreading')
    op.drop_table('telemetryreading')
    # ### end Alembic commands ###
